In [1]:
import numpy as np

In [3]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
array.max()

10

In [10]:
array.min()

1

In [11]:
array.mean()

5.5

In [17]:
array * 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [21]:
np.unique(np.array([1,1,1,1,1,1,1,1,1,1]))

array([1])

In [26]:
np.array([2,3]) * np.array([7,8])

array([14, 24])

In [27]:
np.array(np.mat('1 2; 3 4'), subok=True)

matrix([[1, 2],
        [3, 4]])

In [29]:
np.mat('1 2; 3 4') * 4

matrix([[ 4,  8],
        [12, 16]])

In [32]:
np.mat('1 2; 3 4') * np.mat('5; 3')

matrix([[11],
        [27]])

In [33]:
np.mat('1 2; 3 4') * np.mat('5 1; 3 4')

matrix([[11,  9],
        [27, 19]])